apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-api-location-create
  name: udaconnect-api-location-create
  namespace: udaconnect
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30010
  selector:
    service: udaconnect-api-location-create
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-api-location-create
  name: udaconnect-api-location-create
  namespace: udaconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-api-location-create
  template:
    metadata:
      labels:
        service: udaconnect-api-location-create
    spec:
      containers:
      - image: gdbourne/api-location-create:latest
        name: udaconnect-api-location-create
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: KAFKA_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_ADDRESS
      restartPolicy: Always
