name: Location Consumer Docker CI

on:
  push:
    branches:
      - master
    paths:
      - modules/location-consumer/**
    
  pull_request:
    branches:
      - master
    paths:
      - modules/location-consumer/**

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MODULE
        uses: actions/checkout@v3
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "100"
          path: "./modules/location-consumer/"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/location-consumer/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/location-consumer:latest
