name: api person docker CI

on:
  push:
    branches:
      - master
    paths:
      - modules/api-person/**
    
  pull_request:
    branches:
      - master
    paths:
      - modules/api-person/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./modules/api-person/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-person:latest
